# Generated by Django 5.1.6 on 2025-03-13 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artlibrary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_role',
            field=models.CharField(choices=[('patron', 'Patron'), ('librarian', 'Librarian'), ('anonymous', 'Anonymous')], default='patron', max_length=12),
        ),
    ]
