# Generated by Django 5.1.6 on 2025-03-15 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artlibrary', '0003_artsupply_description_artsupply_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
