# Generated by Django 5.1.6 on 2025-03-15 22:34

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artlibrary', '0006_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artsupply',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='art_supplies/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='profile_pics/'),
        ),
    ]
