# Generated by Django 5.1.6 on 2025-03-23 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artlibrary', '0007_alter_artsupply_image_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='added_by',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='created_collections', to=settings.AUTH_USER_MODEL),
        ),
    ]
