# Generated by Django 5.1.6 on 2025-03-25 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artlibrary', '0008_collection_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='artsupply',
            name='item_type',
            field=models.CharField(choices=[('single', 'Single Use'), ('multi', 'Multi Use')], default='multi', max_length=7),
        ),
        migrations.AddField(
            model_name='artsupply',
            name='use_policy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(blank=True, max_length=100, null=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='artlibrary.artsupply')),
            ],
        ),
    ]
