# Generated by Django 5.1.6 on 2025-03-27 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artlibrary', '0009_artsupply_item_type_artsupply_use_policy_keyword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artsupply',
            name='collection',
        ),
        migrations.AddField(
            model_name='artsupply',
            name='private_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='private_items', to='artlibrary.collection'),
        ),
        migrations.AddField(
            model_name='artsupply',
            name='public_collections',
            field=models.ManyToManyField(blank=True, related_name='public_items', to='artlibrary.collection'),
        ),
    ]
