# Generated by Django 5.1.6 on 2025-03-27 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artlibrary', '0011_remove_artsupply_private_collection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artsupply',
            name='collection',
            field=models.ManyToManyField(blank=True, related_name='items', to='artlibrary.collection'),
        ),
    ]
