# Generated by Django 5.1.6 on 2025-03-27 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artlibrary', '0012_alter_artsupply_collection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Keyword',
        ),
    ]
