# Generated by Django 5.1.6 on 2025-03-31 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artlibrary', '0013_delete_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='art_supplies',
            field=models.ManyToManyField(blank=True, related_name='collections_in', to='artlibrary.artsupply'),
        ),
    ]
