# Generated by Django 5.1.6 on 2025-03-28 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artlibrary', '0013_delete_keyword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artsupply',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='num_items',
        ),
        migrations.AddField(
            model_name='collection',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='inCollections', to='artlibrary.artsupply'),
        ),
    ]
