# Generated by Django 5.1.6 on 2025-03-31 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artlibrary', '0014_collection_art_supplies'),
        ('artlibrary', '0014_remove_artsupply_collection_and_more'),
    ]

    operations = [
    ]
