# Generated by Django 5.1.6 on 2025-03-31 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artlibrary', '0015_merge_20250331_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='items',
        ),
        migrations.AddField(
            model_name='collection',
            name='num_items',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
