# Generated by Django 5.1.6 on 2025-04-04 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artlibrary', '0016_remove_collection_items_collection_num_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtSupplyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('librarian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_requests', to=settings.AUTH_USER_MODEL)),
                ('patron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CollectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('librarian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_requests', to=settings.AUTH_USER_MODEL)),
                ('patron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_collections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
