# Generated by Django 5.1.6 on 2025-04-04 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artlibrary', '0017_artsupplyrequest_collectionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='artsupplyrequest',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='requests_for_item', to='artlibrary.artsupply'),
        ),
        migrations.AddField(
            model_name='collectionrequest',
            name='collection',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='requests_for_collection', to='artlibrary.artsupply'),
        ),
    ]
