# Generated by Django 5.1.6 on 2025-04-04 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artlibrary', '0018_artsupplyrequest_item_collectionrequest_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionrequest',
            name='collection',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='requests_for_collection', to='artlibrary.collection'),
        ),
    ]
