# Generated by Django 5.1.6 on 2025-04-08 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artlibrary', '0019_alter_collectionrequest_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='artsupplyrequest',
            name='lending_period',
            field=models.TextField(blank=True, null=True),
        ),
    ]
