# Generated by Django 5.1.6 on 2025-04-08 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artlibrary', '0020_artsupplyrequest_lending_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='artsupply',
            name='borrowed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
