# Generated by Django 5.1.6 on 2025-04-22 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artlibrary', '0021_artsupply_borrowed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='artsupply',
            name='borrow_history',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_previously_borrowed', to=settings.AUTH_USER_MODEL),
        ),
    ]
