# Generated by Django 5.1.6 on 2025-04-22 14:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artlibrary', '0022_artsupply_borrow_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artsupply',
            name='borrow_history',
        ),
        migrations.AddField(
            model_name='artsupply',
            name='borrow_history',
            field=models.ManyToManyField(blank=True, related_name='items_previously_borrowed', to=settings.AUTH_USER_MODEL),
        ),
    ]
